# apps/arr/sonarr.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          ports:
            - containerPort: 8989
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "100"
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: TZ
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          hostPath:
            path: /home/cif/homelab/config/sonarr
            type: DirectoryOrCreate
        - name: data
          hostPath:
            path: /home/cif/homelab/data
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  type: LoadBalancer
  ports:
    - port: 8989
      targetPort: 8989
  selector:
    app: sonarr
