# apps/databases/immich-db.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-db
  template:
    metadata:
      labels:
        app: immich-db
    spec:
      containers:
        - name: postgres
          image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
          env:
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: TZ
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "immich"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
            - name: POSTGRES_INITDB_ARGS
              value: "--data-checksums"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: IMMICH_DB_PASSWORD
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          hostPath:
            path: /home/cif/homelab/config/immich-db
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: immich-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: immich-db
