# apps/databases/immich-db.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-db
  template:
    metadata:
      labels:
        app: immich-db
    spec:
      containers:
        - name: postgres
          image: tensorchord/pgvecto-rs:pg14-v0.2.0
          args: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", "search_path=\"$$user\", public, vectors", "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
          env:
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: TZ
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "immich"
            - name: PGDATA 
              value: "/var/lib/postgresql/data/pgdata"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: IMMICH_DB_PASSWORD
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          hostPath:
            path: /home/cif/homelab/config/immich-db
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: immich-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: immich-db
