# apps/downloads/metube.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metube
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metube
  template:
    metadata:
      labels:
        app: metube
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
      containers:
        - name: metube
          image: ghcr.io/alexta69/metube:latest
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          env:
            - name: UID
              value: "1000"
            - name: GID
              value: "100"
            - name: UMASK
              value: "002"
            - name: DOWNLOAD_DIR
              value: "/downloads"
            - name: AUDIO_DOWNLOAD_DIR
              value: "/downloads"
            - name: AUDIO_FORMAT
              value: "mp3"
            - name: OUTPUT_TEMPLATE
              value: "%(title)s.%(ext)s"
          volumeMounts:
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: downloads
          hostPath:
            path: /home/cif/homelab/data/music
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: metube
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: metube
